/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphics;

import processes.Accounting;
import processes.VehiclesManagment;

/**
 *
 * @author Felipe
 */
public class CashCheckout extends javax.swing.JFrame {

    /**
     * Creates new form CashCheckout
     */
    public CashCheckout() {
        initComponents();
        showVehiclesQuantities();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratesTitleLabel = new javax.swing.JLabel();
        graphicsPane = new javax.swing.JPanel();
        vehiclesCounterLabel = new javax.swing.JLabel();
        carCounterLabel = new javax.swing.JLabel();
        motorcycleCounterLabel = new javax.swing.JLabel();
        bikeCounterLabel = new javax.swing.JLabel();
        totalCounterLabel = new javax.swing.JLabel();
        carCounter = new javax.swing.JLabel();
        motorcycleCounter = new javax.swing.JLabel();
        bikeCounter = new javax.swing.JLabel();
        totalCounter = new javax.swing.JLabel();
        generatedCashLabel = new javax.swing.JLabel();
        carCashLabel = new javax.swing.JLabel();
        motorcycleCashLabel = new javax.swing.JLabel();
        bikeCashLabel = new javax.swing.JLabel();
        totalCashLabel = new javax.swing.JLabel();
        carCash = new javax.swing.JLabel();
        motorcycleCash = new javax.swing.JLabel();
        bikeCash = new javax.swing.JLabel();
        totalCash = new javax.swing.JLabel();
        developerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(656, 434));
        setResizable(false);

        ratesTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        ratesTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratesTitleLabel.setText("CUADRE DE CAJA");

        javax.swing.GroupLayout graphicsPaneLayout = new javax.swing.GroupLayout(graphicsPane);
        graphicsPane.setLayout(graphicsPaneLayout);
        graphicsPaneLayout.setHorizontalGroup(
            graphicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        graphicsPaneLayout.setVerticalGroup(
            graphicsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        vehiclesCounterLabel.setText("CONTEO VEHICULOS");

        carCounterLabel.setText("AUTOS:");

        motorcycleCounterLabel.setText("MOTOS:");

        bikeCounterLabel.setText("BICICLETAS:");

        totalCounterLabel.setText("TOTAL:");

        generatedCashLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        generatedCashLabel.setText("DINERO GENERADO");

        carCashLabel.setText("AUTOS:");

        motorcycleCashLabel.setText("MOTOS:");

        bikeCashLabel.setText("BICICLETAS:");

        totalCashLabel.setText("TOTAL:");

        carCash.setText("50000");

        motorcycleCash.setText("10000");

        bikeCash.setText("1000");

        totalCash.setText("61000");

        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(graphicsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bikeCounterLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bikeCounter)
                                .addGap(3, 3, 3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(vehiclesCounterLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(carCounterLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(carCounter))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(motorcycleCounterLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(motorcycleCounter)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(totalCounterLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(totalCounter)))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(carCashLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bikeCash, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(carCash, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bikeCashLabel)
                                    .addComponent(motorcycleCashLabel)
                                    .addComponent(totalCashLabel))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 118, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(motorcycleCash)
                                    .addComponent(totalCash)))
                            .addComponent(generatedCashLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26))
                    .addComponent(developerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(ratesTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphicsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vehiclesCounterLabel)
                            .addComponent(generatedCashLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carCounterLabel)
                            .addComponent(carCashLabel)
                            .addComponent(carCounter)
                            .addComponent(carCash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(motorcycleCounterLabel)
                            .addComponent(motorcycleCashLabel)
                            .addComponent(motorcycleCounter)
                            .addComponent(motorcycleCash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bikeCounterLabel)
                            .addComponent(bikeCashLabel)
                            .addComponent(bikeCounter)
                            .addComponent(bikeCash))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalCounterLabel)
                            .addComponent(totalCashLabel)
                            .addComponent(totalCounter)
                            .addComponent(totalCash))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(developerLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(ratesTitleLabel)
                    .addContainerGap(324, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashCheckout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashCheckout().setVisible(true);
            }
        });
    }
    
    
    protected void showVehiclesQuantities() {
        VehiclesManagment vehiclesManagment = new VehiclesManagment();
        carCounter.setText(String.valueOf(vehiclesManagment.getCarsQuantity()));
        motorcycleCounter.setText(String.valueOf(vehiclesManagment.getMotorcyclesQuantity()));
        bikeCounter.setText(String.valueOf(vehiclesManagment.getBikesQuantity()));
        totalCounter.setText(String.valueOf(vehiclesManagment.getTotalVehicles()));
    }
    
    protected void showIncomes() {
        Accounting accounting = new Accounting();
        carCash.setText(String.valueOf(accounting.getCarsIncome()));
        motorcycleCash.setText(String.valueOf(accounting.getMotorcyclesIncome()));
        bikeCash.setText(String.valueOf(accounting.getBikesIncome()));
        //totalCash.setText(String.valueOf(accounting.getTotalIncome()));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bikeCash;
    private javax.swing.JLabel bikeCashLabel;
    private javax.swing.JLabel bikeCounter;
    private javax.swing.JLabel bikeCounterLabel;
    private javax.swing.JLabel carCash;
    private javax.swing.JLabel carCashLabel;
    private javax.swing.JLabel carCounter;
    private javax.swing.JLabel carCounterLabel;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JLabel generatedCashLabel;
    private javax.swing.JPanel graphicsPane;
    private javax.swing.JLabel motorcycleCash;
    private javax.swing.JLabel motorcycleCashLabel;
    private javax.swing.JLabel motorcycleCounter;
    private javax.swing.JLabel motorcycleCounterLabel;
    private javax.swing.JLabel ratesTitleLabel;
    private javax.swing.JLabel totalCash;
    private javax.swing.JLabel totalCashLabel;
    private javax.swing.JLabel totalCounter;
    private javax.swing.JLabel totalCounterLabel;
    private javax.swing.JLabel vehiclesCounterLabel;
    // End of variables declaration//GEN-END:variables
}
