/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphics;

import utilities.ClearInputsOutputs;

/**
 *
 * @author Felipe
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratesTitleLabel = new javax.swing.JLabel();
        dashboardSearchVehicleButton = new javax.swing.JButton();
        dashboardDepartureVehicleButton = new javax.swing.JButton();
        dashboardTodayRecordsButton = new javax.swing.JButton();
        dashboardGenerateInvoiceButton = new javax.swing.JButton();
        dashboardShowLogsButton = new javax.swing.JButton();
        dashboardRatesButton = new javax.swing.JButton();
        dashboardCloseSessionButton = new javax.swing.JButton();
        dashboardEntryVehicleButton = new javax.swing.JButton();
        dashboardCalculatorButton = new javax.swing.JButton();
        developerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        ratesTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        ratesTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratesTitleLabel.setText("MENU PRINCIPAL");

        dashboardSearchVehicleButton.setText("BUSCAR VEHICULO");
        dashboardSearchVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardSearchVehicleButtonActionPerformed(evt);
            }
        });

        dashboardDepartureVehicleButton.setText("SALIDA VEHICULO");
        dashboardDepartureVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardDepartureVehicleButtonActionPerformed(evt);
            }
        });

        dashboardTodayRecordsButton.setText("CUADRE CAJA");
        dashboardTodayRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardTodayRecordsButtonActionPerformed(evt);
            }
        });

        dashboardGenerateInvoiceButton.setText("GENERAR FACTURA");
        dashboardGenerateInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardGenerateInvoiceButtonActionPerformed(evt);
            }
        });

        dashboardShowLogsButton.setText("MOSTRAR REGISTROS");
        dashboardShowLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardShowLogsButtonActionPerformed(evt);
            }
        });

        dashboardRatesButton.setText("TARIFAS");
        dashboardRatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardRatesButtonActionPerformed(evt);
            }
        });

        dashboardCloseSessionButton.setText("CERRAR SESION");
        dashboardCloseSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardCloseSessionButtonActionPerformed(evt);
            }
        });

        dashboardEntryVehicleButton.setText("ENTRADA VEHICULO");
        dashboardEntryVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardEntryVehicleButtonActionPerformed(evt);
            }
        });

        dashboardCalculatorButton.setText("CALCULADORA");
        dashboardCalculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardCalculatorButtonActionPerformed(evt);
            }
        });

        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(developerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ratesTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardEntryVehicleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardCalculatorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardDepartureVehicleButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardSearchVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardGenerateInvoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardRatesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dashboardTodayRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardShowLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dashboardCloseSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(ratesTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dashboardEntryVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dashboardSearchVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dashboardShowLogsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dashboardGenerateInvoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dashboardDepartureVehicleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dashboardTodayRecordsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dashboardRatesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dashboardCalculatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dashboardCloseSessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(developerLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardSearchVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardSearchVehicleButtonActionPerformed
        SearchVehicle searchVehicle = new SearchVehicle();
        searchVehicle.setVisible(true);
        searchVehicle.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardSearchVehicleButtonActionPerformed

    private void dashboardEntryVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardEntryVehicleButtonActionPerformed
        VehicleCheckIn vehicleCheckIn = new VehicleCheckIn();
        vehicleCheckIn.setVisible(true);
        vehicleCheckIn.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardEntryVehicleButtonActionPerformed

    private void dashboardDepartureVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardDepartureVehicleButtonActionPerformed
        VehicleCheckOut vehicleCheckOut = new VehicleCheckOut();
        vehicleCheckOut.setVisible(true);
        vehicleCheckOut.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardDepartureVehicleButtonActionPerformed

    private void dashboardShowLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardShowLogsButtonActionPerformed
        VehicleLogs vehicleLogs = new VehicleLogs();
        vehicleLogs.setVisible(true);
        vehicleLogs.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardShowLogsButtonActionPerformed

    private void dashboardRatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardRatesButtonActionPerformed
        Rates rates = new Rates();
        rates.setVisible(true);
        rates.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardRatesButtonActionPerformed

    private void dashboardCloseSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardCloseSessionButtonActionPerformed
        ClearInputsOutputs ClearInputsOutputs = new ClearInputsOutputs();
        ClearInputsOutputs.clearUserData();
        Login login = new Login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardCloseSessionButtonActionPerformed

    private void dashboardTodayRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardTodayRecordsButtonActionPerformed
        CashCheckout cashCheckout = new CashCheckout();
        cashCheckout.setVisible(true);
        cashCheckout.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardTodayRecordsButtonActionPerformed

    private void dashboardCalculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardCalculatorButtonActionPerformed
        Calculator calculator = new Calculator();
        calculator.setVisible(true);
        calculator.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardCalculatorButtonActionPerformed

    private void dashboardGenerateInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardGenerateInvoiceButtonActionPerformed
        GenerateInvoice generateInvoice = new GenerateInvoice();
        generateInvoice.setVisible(true);
        generateInvoice.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardGenerateInvoiceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dashboardCalculatorButton;
    private javax.swing.JButton dashboardCloseSessionButton;
    private javax.swing.JButton dashboardDepartureVehicleButton;
    private javax.swing.JButton dashboardEntryVehicleButton;
    private javax.swing.JButton dashboardGenerateInvoiceButton;
    private javax.swing.JButton dashboardRatesButton;
    private javax.swing.JButton dashboardSearchVehicleButton;
    private javax.swing.JButton dashboardShowLogsButton;
    private javax.swing.JButton dashboardTodayRecordsButton;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JLabel ratesTitleLabel;
    // End of variables declaration//GEN-END:variables
}
