/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphics;

import connection.QueryManagment;
import utilities.ParseUserInputs;

/**
 *
 * @author Felipe
 */
public class SearchVehicle extends javax.swing.JFrame {

    /**
     * Creates new form SearchVehicle
     */
    public SearchVehicle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratesTitleLabel = new javax.swing.JLabel();
        inputsContainer = new javax.swing.JPanel();
        searchDiscriminant = new javax.swing.JComboBox<>();
        searchParam = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        resultContainer = new javax.swing.JPanel();
        resultCategoryContainer = new javax.swing.JPanel();
        vehicleTypeLabel = new javax.swing.JLabel();
        vehiclePlateLabel = new javax.swing.JLabel();
        vehicleOwnerLabel = new javax.swing.JLabel();
        vehicleStateLabel = new javax.swing.JLabel();
        inParkingLabel = new javax.swing.JLabel();
        resultPlaceContainer = new javax.swing.JPanel();
        vehicleType = new javax.swing.JLabel();
        vehiclePlate = new javax.swing.JLabel();
        vehicleOwner = new javax.swing.JLabel();
        vehicleState = new javax.swing.JLabel();
        inParking = new javax.swing.JLabel();
        itsNotContainer = new javax.swing.JPanel();
        itsNotLabel = new javax.swing.JLabel();
        developerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        ratesTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        ratesTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratesTitleLabel.setText("BUSCAR VEHICULO");

        searchDiscriminant.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Placa", "Cedula" }));
        searchDiscriminant.setEnabled(false);

        searchParam.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchParam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchParamActionPerformed(evt);
            }
        });

        searchButton.setText("BUSCAR");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        goBack.setText("VOLVER");
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputsContainerLayout = new javax.swing.GroupLayout(inputsContainer);
        inputsContainer.setLayout(inputsContainerLayout);
        inputsContainerLayout.setHorizontalGroup(
            inputsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(searchParam)
                        .addComponent(searchDiscriminant, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputsContainerLayout.setVerticalGroup(
            inputsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchDiscriminant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchParam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(goBack)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        vehicleTypeLabel.setText("TIPO:");

        vehiclePlateLabel.setText("PLACA:");

        vehicleOwnerLabel.setText("PROPIETARIO:");

        vehicleStateLabel.setText("ESTADO:");

        inParkingLabel.setText("EN PARQUEADERO:");

        javax.swing.GroupLayout resultCategoryContainerLayout = new javax.swing.GroupLayout(resultCategoryContainer);
        resultCategoryContainer.setLayout(resultCategoryContainerLayout);
        resultCategoryContainerLayout.setHorizontalGroup(
            resultCategoryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vehiclePlateLabel)
            .addComponent(vehicleTypeLabel)
            .addComponent(vehicleStateLabel)
            .addComponent(inParkingLabel)
            .addComponent(vehicleOwnerLabel)
        );
        resultCategoryContainerLayout.setVerticalGroup(
            resultCategoryContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultCategoryContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vehicleTypeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vehiclePlateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vehicleOwnerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vehicleStateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inParkingLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        vehicleType.setText("------------");

        vehiclePlate.setText("------------");

        vehicleOwner.setText("------------");

        vehicleState.setText("------------");

        inParking.setText("------------");

        javax.swing.GroupLayout resultPlaceContainerLayout = new javax.swing.GroupLayout(resultPlaceContainer);
        resultPlaceContainer.setLayout(resultPlaceContainerLayout);
        resultPlaceContainerLayout.setHorizontalGroup(
            resultPlaceContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPlaceContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultPlaceContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(vehicleType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                    .addComponent(vehiclePlate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleOwner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(vehicleState, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inParking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        resultPlaceContainerLayout.setVerticalGroup(
            resultPlaceContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPlaceContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vehicleType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vehiclePlate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vehicleOwner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(vehicleState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(inParking)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout resultContainerLayout = new javax.swing.GroupLayout(resultContainer);
        resultContainer.setLayout(resultContainerLayout);
        resultContainerLayout.setHorizontalGroup(
            resultContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(resultCategoryContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPlaceContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resultContainerLayout.setVerticalGroup(
            resultContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultPlaceContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(resultCategoryContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(6, 6, 6))
        );

        itsNotLabel.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        itsNotLabel.setForeground(new java.awt.Color(255, 0, 0));
        itsNotLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        itsNotLabel.setText("-");

        javax.swing.GroupLayout itsNotContainerLayout = new javax.swing.GroupLayout(itsNotContainer);
        itsNotContainer.setLayout(itsNotContainerLayout);
        itsNotContainerLayout.setHorizontalGroup(
            itsNotContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(itsNotContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(itsNotLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        itsNotContainerLayout.setVerticalGroup(
            itsNotContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(itsNotLabel, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(developerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(itsNotContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ratesTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputsContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resultContainer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(itsNotContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(developerLabel)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ratesTitleLabel)
                    .addContainerGap(218, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchParamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchParamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchParamActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_goBackActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        //Obtiene el metodo de busqueda y el criterio
        String searchBy = searchDiscriminant.getSelectedItem().toString();
        String search = searchParam.getText().toLowerCase().trim();

        //Busca la informacion del vehiculo en la base de datos
        QueryManagment queryManagment = new QueryManagment();
        String[] vehicleData = queryManagment.searchVehicle(searchBy, search);

        //Valida que el array tenga informacion; Si no la tiene imprime mensaje indicando que no se entrontro coincidencia
        if (vehicleData[0] != null) {
            ParseUserInputs parseUserInputs = new ParseUserInputs();
            
            //Quita mensaje de no se encontro coincidencia
            itsNotLabel.setText("-");
            
            //Imprime la informacion obtenida del vehiculo
            vehicleType.setText(vehicleData[1].toUpperCase());
            vehiclePlate.setText(vehicleData[8].toUpperCase());
            vehicleOwner.setText(vehicleData[7]);
            vehicleState.setText(vehicleData[3].toUpperCase());
            
            
            //Si vehicleData[6] (QUE ES CHECKOUT_BY) es 0 indica que el vehiculo no ha salido del parqueadero
            if(vehicleData[6].equals("0")) {
                inParking.setText("SI");
            } else {
                inParking.setText("NO");
            }
            
        } else {
            vehicleType.setText("------------");
            vehiclePlate.setText("------------");
            vehicleOwner.setText("------------");
            vehicleState.setText("------------");
            inParking.setText("------------");
            itsNotLabel.setText("NO SE ENCONTRO COINCIDENCIA");
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchVehicle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchVehicle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developerLabel;
    private javax.swing.JButton goBack;
    private javax.swing.JLabel inParking;
    private javax.swing.JLabel inParkingLabel;
    private javax.swing.JPanel inputsContainer;
    private javax.swing.JPanel itsNotContainer;
    private javax.swing.JLabel itsNotLabel;
    private javax.swing.JLabel ratesTitleLabel;
    private javax.swing.JPanel resultCategoryContainer;
    private javax.swing.JPanel resultContainer;
    private javax.swing.JPanel resultPlaceContainer;
    private javax.swing.JButton searchButton;
    private javax.swing.JComboBox<String> searchDiscriminant;
    private javax.swing.JTextField searchParam;
    private javax.swing.JLabel vehicleOwner;
    private javax.swing.JLabel vehicleOwnerLabel;
    private javax.swing.JLabel vehiclePlate;
    private javax.swing.JLabel vehiclePlateLabel;
    private javax.swing.JLabel vehicleState;
    private javax.swing.JLabel vehicleStateLabel;
    private javax.swing.JLabel vehicleType;
    private javax.swing.JLabel vehicleTypeLabel;
    // End of variables declaration//GEN-END:variables
}
