/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package graphics;

import javax.swing.JOptionPane;
import managmentCore.RatesManagment;
import utilities.EmptyPlaces;

/**
 *
 * @author Felipe
 */
public class VehicleCheckOut extends javax.swing.JFrame {

    /**
     * Creates new form VehicleCheckIn
     */
    public VehicleCheckOut() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        vehicleCheckInTitleLabel = new javax.swing.JLabel();
        vehiclesDepartureVehicleState = new javax.swing.JComboBox<>();
        vehiclesDepartureOwnerID = new javax.swing.JTextField();
        vehiclesDepartureCarPlate = new javax.swing.JTextField();
        vehiclesDepartureButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        developerLabel = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        vehicleCheckInTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        vehicleCheckInTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicleCheckInTitleLabel.setText("SALIDA VEHICULAR");

        vehiclesDepartureVehicleState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        vehiclesDepartureOwnerID.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        vehiclesDepartureCarPlate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        vehiclesDepartureCarPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclesDepartureCarPlateActionPerformed(evt);
            }
        });

        vehiclesDepartureButton.setText("INGRESAR");
        vehiclesDepartureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclesDepartureButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("<-");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vehicleCheckInTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(developerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(vehiclesDepartureVehicleState, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vehiclesDepartureButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(vehiclesDepartureCarPlate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(vehiclesDepartureOwnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vehicleCheckInTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(vehiclesDepartureOwnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehiclesDepartureCarPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehiclesDepartureVehicleState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(vehiclesDepartureButton)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goBackButton)
                    .addComponent(developerLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vehiclesDepartureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclesDepartureButtonActionPerformed
        EmptyPlaces emptyPlaces = new EmptyPlaces();
        String[] vehicleData = new String[3], places = {"estado", "cedula", "placa"};;

        vehicleData[0] = vehiclesDepartureVehicleState.getSelectedItem().toString();
        vehicleData[1] = vehiclesDepartureOwnerID.getText().toString().toLowerCase().trim();
        vehicleData[2] = vehiclesDepartureCarPlate.getText().toString().toLowerCase().trim();

        try {
            boolean isEmpty = emptyPlaces.validateEmptyPlaces(vehicleData, places, this, 3);

            if (!isEmpty) {
                searchVehicleToDeparture(vehicleData[2]);
                //confirmDeparture(resultData);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_vehiclesDepartureButtonActionPerformed

    private String[] getVehicleDataToDeparture(String plate) {
        String[] vehicleData = new String[6];
 
        /*
        vehicleData[0] = rs.getString("vehicle_type");
        vehicleData[1] = rs.getString("vehicle_color");
        vehicleData[2] = rs.getString("vehicle_state");
        vehicleData[3] = rs.getString("vehicle_owner_id");
        vehicleData[4] = rs.getString("vehicle_plate");
        vehicleData[5] = rs.getString("checkout");
        */
        
        return vehicleData;
    }
    
    private void searchVehicleToDeparture(String plate) {
        boolean vehicleExists = true;
        String vehicleCheckout = null;
        /*
        Busca la placa del vehiculo en la base de datos; Si hay coincidencia obtiene todos los datos del vehiculo 
        (ESPECIALMENTE EL TIPO DE VEHICULO Y HORA DE ENTRADA)
        */
        
        if(vehicleExists) {
            String [] vehicleData = getVehicleDataToDeparture(plate);
            if(vehicleData[5] != null) {
                confirmDeparture(vehicleData);
            } else {
                JOptionPane.showMessageDialog(this, "El vehiculo ya no esta en el parqueadero");
            }
        } else {
            JOptionPane.showMessageDialog(this, "El vehiculo no fue encontrado");
        }
    }
    
    private void confirmDeparture(String [] vehicleData) {
        double parkingPrice;
        int rateType = JOptionPane.showConfirmDialog(this, "Desea cobrar la tarifa regular?");
        
        if (rateType == 0) {
            RatesManagment ratesManagment = new RatesManagment();
            
            if(vehicleData[0].equals("carro")) {
                parkingPrice = ratesManagment.getCarRate();
            } else if(vehicleData[0].equals("moto")) {
                parkingPrice = ratesManagment.getMotorcycle();
            } else if(vehicleData[0].equals("bicicleta")) {
                parkingPrice = ratesManagment.getBikeRate();
            }
        } else if (rateType == 1) {
            parkingPrice = Double.parseDouble(JOptionPane.showInputDialog("Ingrese el valor a cobrar"));
        }
        
        
        //Obtiene la hora de salida
        //Crea la factura con todos los datos
        //Realiza insercion salida en base de datos
            
    }

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        Dashboard dashboard = new Dashboard();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void vehiclesDepartureCarPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclesDepartureCarPlateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehiclesDepartureCarPlateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VehicleCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VehicleCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VehicleCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VehicleCheckOut.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VehicleCheckOut().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developerLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel vehicleCheckInTitleLabel;
    private javax.swing.JButton vehiclesDepartureButton;
    private javax.swing.JTextField vehiclesDepartureCarPlate;
    private javax.swing.JTextField vehiclesDepartureOwnerID;
    private javax.swing.JComboBox<String> vehiclesDepartureVehicleState;
    // End of variables declaration//GEN-END:variables
}
