/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class CalculatorUI extends javax.swing.JFrame {

    private short operation = 0, repeat = 1;
    private static double number1 = 0, number2 = 0, result = 0;
    private String numberString = "";

    public CalculatorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calculatorTitleLabel = new javax.swing.JLabel();
        resultTextField = new javax.swing.JTextField();
        preResultTextField = new javax.swing.JTextField();
        numberPadContainer = new javax.swing.JPanel();
        numberOneButton = new javax.swing.JButton();
        numberTwoButton = new javax.swing.JButton();
        numberThreeButton = new javax.swing.JButton();
        numberFourButton = new javax.swing.JButton();
        numberFiveButton = new javax.swing.JButton();
        numberSixButton = new javax.swing.JButton();
        numberSevenButton = new javax.swing.JButton();
        numberEightButton = new javax.swing.JButton();
        numberNineButton = new javax.swing.JButton();
        numberZeroButton = new javax.swing.JButton();
        clearFieldsButton = new javax.swing.JButton();
        clearAllButton = new javax.swing.JButton();
        equalsButton = new javax.swing.JButton();
        operationsContainer = new javax.swing.JPanel();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        multiplyButton = new javax.swing.JButton();
        divisionButton = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        developerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        calculatorTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 24)); // NOI18N
        calculatorTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calculatorTitleLabel.setText("CALCULADORA");

        resultTextField.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        resultTextField.setForeground(new java.awt.Color(255, 255, 255));
        resultTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        resultTextField.setText("-");
        resultTextField.setEnabled(false);

        preResultTextField.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        preResultTextField.setForeground(new java.awt.Color(255, 255, 255));
        preResultTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        preResultTextField.setText("-");
        preResultTextField.setEnabled(false);

        numberOneButton.setBackground(new java.awt.Color(204, 204, 204));
        numberOneButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberOneButton.setForeground(new java.awt.Color(0, 0, 0));
        numberOneButton.setText("1");
        numberOneButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberOneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberOneButtonActionPerformed(evt);
            }
        });

        numberTwoButton.setBackground(new java.awt.Color(204, 204, 204));
        numberTwoButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberTwoButton.setForeground(new java.awt.Color(0, 0, 0));
        numberTwoButton.setText("2");
        numberTwoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberTwoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberTwoButtonActionPerformed(evt);
            }
        });

        numberThreeButton.setBackground(new java.awt.Color(204, 204, 204));
        numberThreeButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberThreeButton.setForeground(new java.awt.Color(0, 0, 0));
        numberThreeButton.setText("3");
        numberThreeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberThreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberThreeButtonActionPerformed(evt);
            }
        });

        numberFourButton.setBackground(new java.awt.Color(204, 204, 204));
        numberFourButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberFourButton.setForeground(new java.awt.Color(0, 0, 0));
        numberFourButton.setText("4");
        numberFourButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberFourButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFourButtonActionPerformed(evt);
            }
        });

        numberFiveButton.setBackground(new java.awt.Color(204, 204, 204));
        numberFiveButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberFiveButton.setForeground(new java.awt.Color(0, 0, 0));
        numberFiveButton.setText("5");
        numberFiveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberFiveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberFiveButtonActionPerformed(evt);
            }
        });

        numberSixButton.setBackground(new java.awt.Color(204, 204, 204));
        numberSixButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberSixButton.setForeground(new java.awt.Color(0, 0, 0));
        numberSixButton.setText("6");
        numberSixButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberSixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSixButtonActionPerformed(evt);
            }
        });

        numberSevenButton.setBackground(new java.awt.Color(204, 204, 204));
        numberSevenButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberSevenButton.setForeground(new java.awt.Color(0, 0, 0));
        numberSevenButton.setText("7");
        numberSevenButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberSevenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberSevenButtonActionPerformed(evt);
            }
        });

        numberEightButton.setBackground(new java.awt.Color(204, 204, 204));
        numberEightButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberEightButton.setForeground(new java.awt.Color(0, 0, 0));
        numberEightButton.setText("8");
        numberEightButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberEightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberEightButtonActionPerformed(evt);
            }
        });

        numberNineButton.setBackground(new java.awt.Color(204, 204, 204));
        numberNineButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberNineButton.setForeground(new java.awt.Color(0, 0, 0));
        numberNineButton.setText("9");
        numberNineButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberNineButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberNineButtonActionPerformed(evt);
            }
        });

        numberZeroButton.setBackground(new java.awt.Color(204, 204, 204));
        numberZeroButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        numberZeroButton.setForeground(new java.awt.Color(0, 0, 0));
        numberZeroButton.setText("0");
        numberZeroButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numberZeroButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberZeroButtonActionPerformed(evt);
            }
        });

        clearFieldsButton.setBackground(new java.awt.Color(0, 102, 153));
        clearFieldsButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        clearFieldsButton.setForeground(new java.awt.Color(255, 255, 255));
        clearFieldsButton.setText("-");
        clearFieldsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearFieldsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFieldsButtonActionPerformed(evt);
            }
        });

        clearAllButton.setBackground(new java.awt.Color(204, 0, 0));
        clearAllButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        clearAllButton.setForeground(new java.awt.Color(255, 255, 255));
        clearAllButton.setText("---");
        clearAllButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAllButtonActionPerformed(evt);
            }
        });

        equalsButton.setBackground(new java.awt.Color(0, 153, 51));
        equalsButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        equalsButton.setForeground(new java.awt.Color(255, 255, 255));
        equalsButton.setText("=");
        equalsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        equalsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout numberPadContainerLayout = new javax.swing.GroupLayout(numberPadContainer);
        numberPadContainer.setLayout(numberPadContainerLayout);
        numberPadContainerLayout.setHorizontalGroup(
            numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(numberPadContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearFieldsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(clearAllButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(numberPadContainerLayout.createSequentialGroup()
                    .addGap(4, 4, 4)
                    .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(numberPadContainerLayout.createSequentialGroup()
                            .addComponent(numberOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(numberTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(numberThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(numberPadContainerLayout.createSequentialGroup()
                            .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(numberFourButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(numberSevenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(numberPadContainerLayout.createSequentialGroup()
                                    .addComponent(numberZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(equalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(numberPadContainerLayout.createSequentialGroup()
                                    .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(numberPadContainerLayout.createSequentialGroup()
                                            .addComponent(numberFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(17, 17, 17))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numberPadContainerLayout.createSequentialGroup()
                                            .addComponent(numberEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)))
                                    .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(numberSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(numberNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        numberPadContainerLayout.setVerticalGroup(
            numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numberPadContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(clearFieldsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearAllButton)
                .addContainerGap())
            .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(numberPadContainerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numberTwoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberOneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberThreeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numberFiveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberFourButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberSixButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numberNineButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberSevenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(numberEightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(numberPadContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numberZeroButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(equalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        plusButton.setBackground(new java.awt.Color(0, 153, 51));
        plusButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        plusButton.setForeground(new java.awt.Color(255, 255, 255));
        plusButton.setText("+");
        plusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });

        minusButton.setBackground(new java.awt.Color(204, 0, 0));
        minusButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        minusButton.setForeground(new java.awt.Color(255, 255, 255));
        minusButton.setText("-");
        minusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });

        multiplyButton.setBackground(new java.awt.Color(0, 102, 153));
        multiplyButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        multiplyButton.setForeground(new java.awt.Color(255, 255, 255));
        multiplyButton.setText("*");
        multiplyButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        multiplyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplyButtonActionPerformed(evt);
            }
        });

        divisionButton.setBackground(new java.awt.Color(255, 153, 0));
        divisionButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        divisionButton.setForeground(new java.awt.Color(255, 255, 255));
        divisionButton.setText("/");
        divisionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        divisionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout operationsContainerLayout = new javax.swing.GroupLayout(operationsContainer);
        operationsContainer.setLayout(operationsContainerLayout);
        operationsContainerLayout.setHorizontalGroup(
            operationsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(operationsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );
        operationsContainerLayout.setVerticalGroup(
            operationsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, operationsContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(plusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(minusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(multiplyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(divisionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        goBack.setBackground(new java.awt.Color(204, 0, 0));
        goBack.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        goBack.setForeground(new java.awt.Color(255, 255, 255));
        goBack.setText("<-");
        goBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackActionPerformed(evt);
            }
        });

        developerLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calculatorTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(preResultTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(resultTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(goBack)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(developerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(numberPadContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(operationsContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calculatorTitleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(preResultTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(operationsContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(numberPadContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(developerLabel)
                    .addComponent(goBack))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numberEightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberEightButtonActionPerformed
        numberString += "8";
        printNumber();
    }//GEN-LAST:event_numberEightButtonActionPerformed

    private void clearFieldsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFieldsButtonActionPerformed
        short mode = 1;
        clearNumber(mode);
    }//GEN-LAST:event_clearFieldsButtonActionPerformed

    private void equalsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsButtonActionPerformed
        Enter();
    }//GEN-LAST:event_equalsButtonActionPerformed

    private void goBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackActionPerformed
        DashboardUI dashboard = new DashboardUI();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_goBackActionPerformed

    private void numberOneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberOneButtonActionPerformed
        numberString += "1";
        printNumber();
    }//GEN-LAST:event_numberOneButtonActionPerformed

    private void numberTwoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberTwoButtonActionPerformed
        numberString += "2";
        printNumber();
    }//GEN-LAST:event_numberTwoButtonActionPerformed

    private void numberThreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberThreeButtonActionPerformed
        numberString += "3";
        printNumber();
    }//GEN-LAST:event_numberThreeButtonActionPerformed

    private void numberFourButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFourButtonActionPerformed
        numberString += "4";
        printNumber();
    }//GEN-LAST:event_numberFourButtonActionPerformed

    private void numberFiveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberFiveButtonActionPerformed
        numberString += "5";
        printNumber();
    }//GEN-LAST:event_numberFiveButtonActionPerformed

    private void numberSixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSixButtonActionPerformed
        numberString += "6";
        printNumber();
    }//GEN-LAST:event_numberSixButtonActionPerformed

    private void numberSevenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberSevenButtonActionPerformed
        numberString += "7";
        printNumber();
    }//GEN-LAST:event_numberSevenButtonActionPerformed

    private void numberNineButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberNineButtonActionPerformed
        numberString += "9";
        printNumber();
    }//GEN-LAST:event_numberNineButtonActionPerformed

    private void numberZeroButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberZeroButtonActionPerformed
        numberString += "0";
        printNumber();
    }//GEN-LAST:event_numberZeroButtonActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        Plus();
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        Minus();
    }//GEN-LAST:event_minusButtonActionPerformed

    private void multiplyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplyButtonActionPerformed
        Multiply();
    }//GEN-LAST:event_multiplyButtonActionPerformed

    private void divisionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionButtonActionPerformed
        Division();
    }//GEN-LAST:event_divisionButtonActionPerformed

    private void clearAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAllButtonActionPerformed
        clearAll();
    }//GEN-LAST:event_clearAllButtonActionPerformed

    public void setResult(String result) {
        resultTextField.setText(result);
    }

    public void printNumber() {
        preResultTextField.setText(numberString);
    }

    public void resetVariables() {
        number1 = 0;
        number2 = 0;
    }

    public void buttonSetVisible() {
        plusButton.setEnabled(true);
        minusButton.setEnabled(true);
        multiplyButton.setEnabled(true);
        divisionButton.setEnabled(true);
    }

    public void buttonSetInvisible() {
        plusButton.setEnabled(false);
        minusButton.setEnabled(false);
        multiplyButton.setEnabled(false);
        divisionButton.setEnabled(false);
    }

    public void clearNumber(short mode) {
        if (mode == 1) {
            int numberLength = numberString.length();
            if (numberLength < 1) {
                JOptionPane.showMessageDialog(this, "El campo esta vacío");
            } else {
                numberString = numberString.substring(0, numberLength - 1);
                printNumber();
            }
        } else if (mode == 2) {
            numberString = "";
            result = 0;
            repeat--;
            resetVariables();
            setResult("");
            printNumber();
        }
    }
    
    public boolean clearAll() {
        short mode = 2;
        clearNumber(mode);
        return false;
    }

    public void Enter() {
        if (operation == 1) {
            if (repeat == 1) {
                number2 = Double.parseDouble(numberString);
                numberString = "";
                result = number1 + number2;
                resetVariables();
                printNumber();
                setResult("Resultado: " + result);
                operation = 0;
                repeat++;

                buttonSetVisible();
            } else if (repeat == 2) {
                number2 = Double.parseDouble(numberString);
                numberString = "";
                result += number2;
                resetVariables();
                printNumber();
                setResult("Resultado: " + result);
                operation = 0;

                buttonSetVisible();
            }
        }
        if (operation == 2) {
            if (repeat == 1) {
                number2 = Double.parseDouble(numberString);
                numberString = "";
                result = number1 - number2;
                resetVariables();
                printNumber();
                setResult("Resultado: " + result);
                operation = 0;
                repeat++;

                buttonSetVisible();
            } else if (repeat == 2) {
                number2 = Double.parseDouble(numberString);
                numberString = "";
                result -= number2;
                resetVariables();
                printNumber();
                setResult("Resultado: " + result);
                operation = 0;

                buttonSetVisible();
            }
        }
        if (operation == 3) {
            if (repeat == 1) {
                number2 = Double.parseDouble(numberString);
                numberString = "";
                result = number1 * number2;
                resetVariables();
                printNumber();
                setResult("Resultado: " + result);
                operation = 0;
                repeat++;

                buttonSetVisible();
            } else if (repeat == 2) {
                number2 = Double.parseDouble(numberString);
                numberString = "";
                result *= number2;
                resetVariables();
                printNumber();
                setResult("Resultado: " + result);
                operation = 0;

                buttonSetVisible();
            }
        }
        if (operation == 4) {
            if (repeat == 1) {
                number2 = Double.parseDouble(numberString);
                numberString = "";
                result = number1 / number2;
                resetVariables();
                printNumber();
                setResult("Resultado: " + result);
                operation = 0;
                repeat++;

                buttonSetVisible();
            } else if (repeat == 2) {
                number2 = Double.parseDouble(numberString);
                if (number2 > 0) {
                    numberString = "";
                    result /= number2;
                    resetVariables();
                    printNumber();
                    setResult("Resultado: " + result);
                    operation = 0;

                    buttonSetVisible();
                } else {
                    JOptionPane.showMessageDialog(this, "No se puede dividir por 0");
                    numberString = "";
                    printNumber();
                }
            }
        }
    }

    public void Plus() {
        if (repeat == 1) {
            number1 = Double.parseDouble(numberString);
            numberString = "";
            buttonSetInvisible();
            operation = 1;
        } else if (repeat == 2) {
            buttonSetInvisible();
            operation = 1;
        }
    }

    public void Minus() {
        if (repeat == 1) {
            number1 = Double.parseDouble(numberString);
            numberString = "";
            buttonSetInvisible();
            operation = 2;
        } else if (repeat == 2) {
            buttonSetInvisible();
            operation = 2;
        }
    }

    public void Multiply() {
        if (repeat == 1) {
            number1 = Double.parseDouble(numberString);
            numberString = "";
            buttonSetInvisible();
            operation = 3;
        } else if (repeat == 2) {
            buttonSetInvisible();
            operation = 3;
        }
    }

    public void Division() {
        if (repeat == 1) {
            number1 = Double.parseDouble(numberString);
            numberString = "";
            buttonSetInvisible();
            operation = 4;
        } else if (repeat == 2) {
            buttonSetInvisible();
            operation = 4;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel calculatorTitleLabel;
    private javax.swing.JButton clearAllButton;
    private javax.swing.JButton clearFieldsButton;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JButton divisionButton;
    private javax.swing.JButton equalsButton;
    private javax.swing.JButton goBack;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton multiplyButton;
    private javax.swing.JButton numberEightButton;
    private javax.swing.JButton numberFiveButton;
    private javax.swing.JButton numberFourButton;
    private javax.swing.JButton numberNineButton;
    private javax.swing.JButton numberOneButton;
    private javax.swing.JPanel numberPadContainer;
    private javax.swing.JButton numberSevenButton;
    private javax.swing.JButton numberSixButton;
    private javax.swing.JButton numberThreeButton;
    private javax.swing.JButton numberTwoButton;
    private javax.swing.JButton numberZeroButton;
    private javax.swing.JPanel operationsContainer;
    private javax.swing.JButton plusButton;
    private javax.swing.JTextField preResultTextField;
    private javax.swing.JTextField resultTextField;
    // End of variables declaration//GEN-END:variables
}
