/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import network.Checkout;
import utilities.IOOperations;
import utilities.TimeMethods;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Felipe
 */
public class CashCheckoutUI extends javax.swing.JFrame {

    /**
     * Creates new form CashCheckout
     */
    public CashCheckoutUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratesTitleLabel = new javax.swing.JLabel();
        todayReport = new javax.swing.JButton();
        otherDayReport = new javax.swing.JButton();
        otherDayReportField = new javax.swing.JTextField();
        otherDaySearchReport = new javax.swing.JButton();
        logsView = new javax.swing.JScrollPane();
        logsViewTable = new javax.swing.JTable();
        goBackButton = new javax.swing.JButton();
        developerLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        ratesTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 24)); // NOI18N
        ratesTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratesTitleLabel.setText("CUADRE DE CAJA");

        todayReport.setBackground(new java.awt.Color(0, 153, 51));
        todayReport.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        todayReport.setForeground(new java.awt.Color(255, 255, 255));
        todayReport.setText("HOY");
        todayReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        todayReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayReportActionPerformed(evt);
            }
        });

        otherDayReport.setBackground(new java.awt.Color(0, 102, 153));
        otherDayReport.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        otherDayReport.setForeground(new java.awt.Color(255, 255, 255));
        otherDayReport.setText("OTRO");
        otherDayReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        otherDayReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherDayReportActionPerformed(evt);
            }
        });

        otherDayReportField.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        otherDayReportField.setForeground(new java.awt.Color(0, 102, 153));
        otherDayReportField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        otherDayReportField.setEnabled(false);

        otherDaySearchReport.setBackground(new java.awt.Color(0, 153, 51));
        otherDaySearchReport.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        otherDaySearchReport.setForeground(new java.awt.Color(255, 255, 255));
        otherDaySearchReport.setText("BUSCAR");
        otherDaySearchReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        otherDaySearchReport.setEnabled(false);
        otherDaySearchReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherDaySearchReportActionPerformed(evt);
            }
        });

        logsViewTable.setAutoCreateRowSorter(true);
        logsViewTable.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        logsViewTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "TIPO", "COBRO", "NOMBRE", "APELLIDO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        logsViewTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        logsViewTable.setShowGrid(true);
        logsViewTable.getTableHeader().setReorderingAllowed(false);
        logsView.setViewportView(logsViewTable);

        goBackButton.setBackground(new java.awt.Color(204, 0, 0));
        goBackButton.setForeground(new java.awt.Color(255, 255, 255));
        goBackButton.setText("<-");
        goBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        developerLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratesTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(developerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(otherDayReportField)
                                    .addComponent(otherDaySearchReport, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(todayReport, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(otherDayReport, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(logsView, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ratesTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(todayReport)
                            .addComponent(otherDayReport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherDayReportField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherDaySearchReport)
                        .addGap(0, 143, Short.MAX_VALUE))
                    .addComponent(logsView, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(developerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goBackButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        //Regresa a la pagina principal
        DashboardUI dashboard = new DashboardUI();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void otherDayReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherDayReportActionPerformed
        //Activa el campo para ingresar la fecha
        if (!otherDayReportField.isEnabled()) {
            otherDayReportField.setEnabled(true);
            otherDaySearchReport.setEnabled(true);
        }
    }//GEN-LAST:event_otherDayReportActionPerformed

    private void todayReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayReportActionPerformed
        //Obtiene la fecha actual
        String actualDate = TimeMethods.formatDate();

        //Establece la fecha actual en el campo de texto
        otherDayReportField.setText(actualDate);

        //Desactiva el campo de texto y activa el boton de busqueda
        otherDayReportField.setEnabled(false);
        otherDaySearchReport.setEnabled(true);
    }//GEN-LAST:event_todayReportActionPerformed

    private void otherDaySearchReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherDaySearchReportActionPerformed
        // Obtiene la fecha ingresada y la formatea
        String dateToSearch = IOOperations.replaceSlash(otherDayReportField.getText());

        // Obtiene el conteo y los totales desde la base de datos
        Checkout queryCheckoutData = new Checkout();
        String[][] checkoutData = queryCheckoutData.getCheckoutData(dateToSearch);

        fillTable(checkoutData);
    }//GEN-LAST:event_otherDaySearchReportActionPerformed

    private void fillTable(String[][] logsData) {
        if (logsData == null || logsData.length == 0) {
            JOptionPane.showMessageDialog(this, "No se encontraron registros");
            return;
        }

        // Instancia el modelo de la tabla
        DefaultTableModel tableModel = (DefaultTableModel) logsViewTable.getModel();

        // Limpia la tabla para eliminar elementos anteriores
        clearTable(tableModel);

        // Agrega las filas a la tabla
        for (String[] rowData : logsData) {
            Object[] row = new Object[5];
            System.arraycopy(rowData, 0, row, 0, rowData.length);
            tableModel.addRow(row);
        }
    }

    private void clearTable(DefaultTableModel tableModel) {
        tableModel.setRowCount(0);  // Resetea directamente las filas de la tabla
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashCheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashCheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashCheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashCheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashCheckoutUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developerLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JScrollPane logsView;
    private javax.swing.JTable logsViewTable;
    private javax.swing.JButton otherDayReport;
    private javax.swing.JTextField otherDayReportField;
    private javax.swing.JButton otherDaySearchReport;
    private javax.swing.JLabel ratesTitleLabel;
    private javax.swing.JButton todayReport;
    // End of variables declaration//GEN-END:variables
}
