/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Felipe
 */
public class DashboardUI extends javax.swing.JFrame {
    /**
     * Creates new form Dashboard
     */
    public DashboardUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratesTitleLabel = new javax.swing.JLabel();
        dashboardEntryVehicleButton = new javax.swing.JButton();
        dashboardSearchVehicleButton = new javax.swing.JButton();
        dashboardShowLogsButton = new javax.swing.JButton();
        dashboardDepartureVehicleButton = new javax.swing.JButton();
        dashboardGenerateInvoiceButton = new javax.swing.JButton();
        dashboardTodayRecordsButton = new javax.swing.JButton();
        dashboardCalculatorButton = new javax.swing.JButton();
        dashboardRatesButton = new javax.swing.JButton();
        dashboardCloseSessionButton = new javax.swing.JButton();
        branding = new javax.swing.JPanel();
        developerLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("dashboard"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ratesTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 24)); // NOI18N
        ratesTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        ratesTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratesTitleLabel.setText("MENU PRINCIPAL");
        getContentPane().add(ratesTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 590, 50));

        dashboardEntryVehicleButton.setBackground(new java.awt.Color(0, 153, 51));
        dashboardEntryVehicleButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        dashboardEntryVehicleButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardEntryVehicleButton.setText("REGISTRAR ENTRADA");
        dashboardEntryVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardEntryVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardEntryVehicleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardEntryVehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 180, 100));

        dashboardSearchVehicleButton.setBackground(new java.awt.Color(0, 102, 153));
        dashboardSearchVehicleButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        dashboardSearchVehicleButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardSearchVehicleButton.setText("BUSCAR ARTICULO");
        dashboardSearchVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardSearchVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardSearchVehicleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardSearchVehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 180, 100));

        dashboardShowLogsButton.setBackground(new java.awt.Color(0, 102, 153));
        dashboardShowLogsButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        dashboardShowLogsButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardShowLogsButton.setText("MOSTRAR REGISTROS");
        dashboardShowLogsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardShowLogsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardShowLogsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardShowLogsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 180, 100));

        dashboardDepartureVehicleButton.setBackground(new java.awt.Color(204, 0, 0));
        dashboardDepartureVehicleButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        dashboardDepartureVehicleButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardDepartureVehicleButton.setText("REGISTRAR SALIDA");
        dashboardDepartureVehicleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardDepartureVehicleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardDepartureVehicleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardDepartureVehicleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 180, 100));

        dashboardGenerateInvoiceButton.setBackground(new java.awt.Color(0, 102, 153));
        dashboardGenerateInvoiceButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        dashboardGenerateInvoiceButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardGenerateInvoiceButton.setText("GENERAR FACTURA");
        dashboardGenerateInvoiceButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardGenerateInvoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardGenerateInvoiceButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardGenerateInvoiceButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 180, 100));

        dashboardTodayRecordsButton.setBackground(new java.awt.Color(0, 102, 153));
        dashboardTodayRecordsButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        dashboardTodayRecordsButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardTodayRecordsButton.setText("CUADRE CAJA");
        dashboardTodayRecordsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardTodayRecordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardTodayRecordsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardTodayRecordsButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 180, 100));

        dashboardCalculatorButton.setBackground(new java.awt.Color(255, 255, 255));
        dashboardCalculatorButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        dashboardCalculatorButton.setForeground(new java.awt.Color(0, 102, 153));
        dashboardCalculatorButton.setText("CALCULADORA");
        dashboardCalculatorButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardCalculatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardCalculatorButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardCalculatorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 180, 100));

        dashboardRatesButton.setBackground(new java.awt.Color(0, 102, 153));
        dashboardRatesButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        dashboardRatesButton.setForeground(new java.awt.Color(255, 255, 255));
        dashboardRatesButton.setText("PRECIOS");
        dashboardRatesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardRatesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardRatesButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardRatesButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 180, 100));

        dashboardCloseSessionButton.setBackground(new java.awt.Color(255, 255, 255));
        dashboardCloseSessionButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        dashboardCloseSessionButton.setForeground(new java.awt.Color(0, 102, 153));
        dashboardCloseSessionButton.setText("CERRAR SESION");
        dashboardCloseSessionButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardCloseSessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardCloseSessionButtonActionPerformed(evt);
            }
        });
        getContentPane().add(dashboardCloseSessionButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, 180, 100));

        branding.setBackground(new java.awt.Color(255, 255, 255));

        developerLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        developerLabel.setForeground(new java.awt.Color(0, 0, 0));
        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        javax.swing.GroupLayout brandingLayout = new javax.swing.GroupLayout(branding);
        branding.setLayout(brandingLayout);
        brandingLayout.setHorizontalGroup(
            brandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(developerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        brandingLayout.setVerticalGroup(
            brandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(developerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(branding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 600, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpeg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardSearchVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardSearchVehicleButtonActionPerformed
        SearchItemUI searchVehicle = new SearchItemUI();
        searchVehicle.setVisible(true);
        searchVehicle.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardSearchVehicleButtonActionPerformed

    private void dashboardDepartureVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardDepartureVehicleButtonActionPerformed
        ItemCheckOutUI vehicleCheckOut = new ItemCheckOutUI();
        vehicleCheckOut.setVisible(true);
        vehicleCheckOut.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardDepartureVehicleButtonActionPerformed

    private void dashboardShowLogsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardShowLogsButtonActionPerformed
        ItemLogsUI vehicleLogs = new ItemLogsUI();
        vehicleLogs.setVisible(true);
        vehicleLogs.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardShowLogsButtonActionPerformed

    private void dashboardRatesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardRatesButtonActionPerformed
        RatesUI rates = new RatesUI();
        rates.setVisible(true);
        rates.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardRatesButtonActionPerformed

    private void dashboardCloseSessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardCloseSessionButtonActionPerformed
        LoginUI login = new LoginUI();
        login.setVisible(true);
        login.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardCloseSessionButtonActionPerformed

    private void dashboardTodayRecordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardTodayRecordsButtonActionPerformed
        CashCheckoutUI cashCheckout = new CashCheckoutUI();
        cashCheckout.setVisible(true);
        cashCheckout.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardTodayRecordsButtonActionPerformed

    private void dashboardCalculatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardCalculatorButtonActionPerformed
        CalculatorUI calculator = new CalculatorUI();
        calculator.setVisible(true);
        calculator.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardCalculatorButtonActionPerformed

    private void dashboardGenerateInvoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardGenerateInvoiceButtonActionPerformed
        GenerateInvoiceUI generateInvoice = new GenerateInvoiceUI();
        generateInvoice.setVisible(true);
        generateInvoice.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardGenerateInvoiceButtonActionPerformed

    private void dashboardEntryVehicleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardEntryVehicleButtonActionPerformed
        ItemCheckInUI vehicleCheckIn = new ItemCheckInUI();
        vehicleCheckIn.setVisible(true);
        vehicleCheckIn.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_dashboardEntryVehicleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel branding;
    private javax.swing.JButton dashboardCalculatorButton;
    private javax.swing.JButton dashboardCloseSessionButton;
    private javax.swing.JButton dashboardDepartureVehicleButton;
    private javax.swing.JButton dashboardEntryVehicleButton;
    private javax.swing.JButton dashboardGenerateInvoiceButton;
    private javax.swing.JButton dashboardRatesButton;
    private javax.swing.JButton dashboardSearchVehicleButton;
    private javax.swing.JButton dashboardShowLogsButton;
    private javax.swing.JButton dashboardTodayRecordsButton;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JLabel ratesTitleLabel;
    // End of variables declaration//GEN-END:variables
}
