/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import utilities.SystemAuth;
import javax.swing.JOptionPane;

/**
 *
 * @author Felipe
 */
public class ErrorUI extends javax.swing.JFrame {

    /**
     * Creates new form ErrorUI
     */
    public ErrorUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        brandingLabel = new javax.swing.JLabel();
        OwnerLabel = new javax.swing.JLabel();
        OwnerCellphoneNumberLabel = new javax.swing.JLabel();
        buttonContainer = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("error"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                formMouseWheelMoved(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brandingLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 24)); // NOI18N
        brandingLabel.setForeground(new java.awt.Color(255, 255, 255));
        brandingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        brandingLabel.setText("CASANAS SOFTWARE");
        getContentPane().add(brandingLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, 302, -1));

        OwnerLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        OwnerLabel.setForeground(new java.awt.Color(255, 255, 255));
        OwnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OwnerLabel.setText("By FELIPE CASAÑAS");
        getContentPane().add(OwnerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 129, 302, 16));

        OwnerCellphoneNumberLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        OwnerCellphoneNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        OwnerCellphoneNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OwnerCellphoneNumberLabel.setText("CONTACTO: 3026029365");
        getContentPane().add(OwnerCellphoneNumberLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 222, 302, 16));

        buttonContainer.setBackground(new java.awt.Color(255, 255, 255));

        exitButton.setBackground(new java.awt.Color(204, 0, 0));
        exitButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("CERRAR PROGRAMA");
        exitButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonContainerLayout = new javax.swing.GroupLayout(buttonContainer);
        buttonContainer.setLayout(buttonContainerLayout);
        buttonContainerLayout.setHorizontalGroup(
            buttonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonContainerLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );
        buttonContainerLayout.setVerticalGroup(
            buttonContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(exitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(buttonContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpeg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void formMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_formMouseWheelMoved
        String response = String.valueOf(JOptionPane.showInputDialog("R U?"));

        if (response.equals("CF")) {
            SystemAuth systemAuth = new SystemAuth();
            String[] systemData = systemAuth.getSystemData();

            JOptionPane.showMessageDialog(this, "Disk serial: " + systemData[0] + "\nBios identifier: " + systemData[1] + "\nS.O-Type: " + systemData[2]);
        }
    }//GEN-LAST:event_formMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ErrorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ErrorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ErrorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ErrorUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ErrorUI().setVisible(true);
            }
        });
    }

    public void autenticationError() {
        JOptionPane.showMessageDialog(this, "¡Error de autenticacion!\nPor favor consulte al proveedor del software para solucionar el problema");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel OwnerCellphoneNumberLabel;
    private javax.swing.JLabel OwnerLabel;
    private javax.swing.JLabel background;
    private javax.swing.JLabel brandingLabel;
    private javax.swing.JPanel buttonContainer;
    private javax.swing.JButton exitButton;
    // End of variables declaration//GEN-END:variables
}
