/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import controller.BusinessModel;
import controller.User;
import utilities.IOOperations;
import java.awt.Color;
import java.util.ArrayList;
import java.util.function.Function;
import javax.swing.JComboBox;
import network.BusinessItems;
import network.Checkout;

/**
 *
 * @author Felipe
 */
public class ItemCheckInUI extends javax.swing.JFrame {

    public ItemCheckInUI() {
        initComponents();

        setRateTypeSelector();
        setColorSelector();
        setStateSelector();

        itemOwnerID.setText("Documento del cliente");
        itemIdentifiquer.setText("Identificador del producto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        vehicleCheckInTitleLabel = new javax.swing.JLabel();
        itemTypeSelector = new javax.swing.JComboBox<>();
        itemColorSelector = new javax.swing.JComboBox<>();
        itemStateSelector = new javax.swing.JComboBox<>();
        itemOwnerID = new javax.swing.JTextField();
        itemIdentifiquer = new javax.swing.JTextField();
        itemEntryButton = new javax.swing.JButton();
        branding = new javax.swing.JPanel();
        goBackButton = new javax.swing.JButton();
        developerLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("itemCheckin"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vehicleCheckInTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 24)); // NOI18N
        vehicleCheckInTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        vehicleCheckInTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicleCheckInTitleLabel.setText("ENTRADA ARTICULO");
        getContentPane().add(vehicleCheckInTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 50));

        itemTypeSelector.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        itemTypeSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        itemTypeSelector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(itemTypeSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 175, -1));

        itemColorSelector.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        itemColorSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        itemColorSelector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(itemColorSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 175, -1));

        itemStateSelector.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        itemStateSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));
        itemStateSelector.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(itemStateSelector, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 175, -1));

        itemOwnerID.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        itemOwnerID.setForeground(new java.awt.Color(0, 102, 153));
        itemOwnerID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemOwnerID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemOwnerIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemOwnerIDFocusLost(evt);
            }
        });
        getContentPane().add(itemOwnerID, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 175, -1));

        itemIdentifiquer.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        itemIdentifiquer.setForeground(new java.awt.Color(0, 102, 153));
        itemIdentifiquer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemIdentifiquer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemIdentifiquerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemIdentifiquerFocusLost(evt);
            }
        });
        getContentPane().add(itemIdentifiquer, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 175, -1));

        itemEntryButton.setBackground(new java.awt.Color(0, 153, 51));
        itemEntryButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        itemEntryButton.setForeground(new java.awt.Color(255, 255, 255));
        itemEntryButton.setText("INGRESAR");
        itemEntryButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        itemEntryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEntryButtonActionPerformed(evt);
            }
        });
        getContentPane().add(itemEntryButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 175, -1));

        branding.setBackground(new java.awt.Color(255, 255, 255));
        branding.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goBackButton.setBackground(new java.awt.Color(204, 0, 0));
        goBackButton.setForeground(new java.awt.Color(255, 255, 255));
        goBackButton.setText("<-");
        goBackButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });
        branding.add(goBackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 70, 30));

        developerLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        developerLabel.setForeground(new java.awt.Color(0, 0, 0));
        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");
        branding.add(developerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 440, 40));

        getContentPane().add(branding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 440, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpeg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        DashboardUI dashboard = new DashboardUI();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void setSelector(JComboBox<String> selector, ArrayList<Object> data, int index) {
        ArrayList<String> names = (ArrayList<String>) data.get(index);

        if (names != null && !names.isEmpty()) {
            names.forEach(name -> selector.addItem(name.toUpperCase()));
        } else {
            System.out.println("No se encontraron elementos para agregar al selector.");
        }
    }

    private void setRateTypeSelector() {
        Checkout queryManagment = new Checkout();
        ArrayList<Object> ratesData = BusinessItems.getRatesName(User.getBusiness_id());
        setSelector(itemTypeSelector, ratesData, 1);
    }

    private void setColorSelector() {
        Checkout queryManagment = new Checkout();
        ArrayList<Object> colors = BusinessItems.getColorsName();
        setSelector(itemColorSelector, colors, 1);
    }

    private void setStateSelector() {
        Checkout queryManagment = new Checkout();
        ArrayList<Object> states = BusinessItems.getStatesName();
        setSelector(itemStateSelector, states, 1);
    }

    private String[] getAndParseComboboxData() {
        String[] itemInputData = new String[5];

        // Procesa cada dato del comboBox y los campos de texto, convirtiéndolos a su código o valor correspondiente
        itemInputData[0] = parseAndConvert(itemTypeSelector, IOOperations::parseVehicleTypeToCode);
        itemInputData[1] = parseAndConvert(itemColorSelector, IOOperations::parseVehicleColorToCode);
        itemInputData[2] = parseAndConvert(itemStateSelector, IOOperations::parseVehicleStateToCode);
        itemInputData[3] = IOOperations.sanitizeInput(itemOwnerID.getText().toString());
        itemInputData[4] = IOOperations.sanitizeInput(itemIdentifiquer.getText().toString());

        return itemInputData;
    }

    private String parseAndConvert(JComboBox<String> selector, Function<String, String> parser) {
        String selectedItem = (String) selector.getSelectedItem();
        return selectedItem != null ? parser.apply(selectedItem.toLowerCase()) : "";
    }


    private void itemEntryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEntryButtonActionPerformed
        // Definir los campos a verificar y los datos a ingresar
        String[] fields = {"tipo", "color", "estado", "cedula", "placa"};
        String[] itemInputData = getAndParseComboboxData();

        // Validar que no haya campos vacíos
        if (IOOperations.validateNonEmptyFields(this, itemInputData, fields)) {
            new BusinessModel().checkIn(this, itemInputData, fields);
        }
    }//GEN-LAST:event_itemEntryButtonActionPerformed

    private void itemOwnerIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemOwnerIDFocusGained
        String placeholder = "Documento del cliente";

        // Eliminar el placeholder al ganar foco
        if (itemOwnerID.getText().equals(placeholder)) {
            itemOwnerID.setText("");
            itemOwnerID.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_itemOwnerIDFocusGained

    private void itemOwnerIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemOwnerIDFocusLost
        String placeholder = "Documento del cliente";

        // Restaurar el placeholder si el campo está vacío
        if (itemOwnerID.getText().isEmpty()) {
            itemOwnerID.setText(placeholder);
            itemOwnerID.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_itemOwnerIDFocusLost

    private void itemIdentifiquerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemIdentifiquerFocusGained
        String placeholder = "Identificador del producto";

        // Eliminar el placeholder al ganar foco
        if (itemIdentifiquer.getText().equals(placeholder)) {
            itemIdentifiquer.setText("");
            itemIdentifiquer.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_itemIdentifiquerFocusGained

    private void itemIdentifiquerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemIdentifiquerFocusLost
        String placeholder = "Identificador del producto";

        // Restaurar el placeholder si el campo está vacío
        if (itemIdentifiquer.getText().isEmpty()) {
            itemIdentifiquer.setText(placeholder);
            itemIdentifiquer.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_itemIdentifiquerFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemCheckInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemCheckInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemCheckInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemCheckInUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemCheckInUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel branding;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JComboBox<String> itemColorSelector;
    private javax.swing.JButton itemEntryButton;
    private javax.swing.JTextField itemIdentifiquer;
    private javax.swing.JTextField itemOwnerID;
    private javax.swing.JComboBox<String> itemStateSelector;
    private javax.swing.JComboBox<String> itemTypeSelector;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel vehicleCheckInTitleLabel;
    // End of variables declaration//GEN-END:variables
}
