/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import controller.BusinessModel;
import utilities.IOOperations;
import utilities.Printing;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JComboBox;
import network.BusinessItems;
import network.Item;
import network.Checkout;

/**
 *
 * @author Felipe
 */
public class ItemCheckOutUI extends javax.swing.JFrame {

    public ItemCheckOutUI() {
        initComponents();

        setStateSelector();

        itemDepartureOwnerID.setText("Documento del cliente");
        itemDepartureOwnerID.setForeground(Color.GRAY);

        itemDepartureIdentifiquer.setText("Identificador del producto");
        itemDepartureIdentifiquer.setForeground(Color.GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        vehicleCheckInTitleLabel = new javax.swing.JLabel();
        itemDepartureState = new javax.swing.JComboBox<>();
        itemDepartureOwnerID = new javax.swing.JTextField();
        itemDepartureIdentifiquer = new javax.swing.JTextField();
        itemDepartureButton = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();
        developerLabel = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        vehicleCheckInTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        vehicleCheckInTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vehicleCheckInTitleLabel.setText("SALIDA ARTICULO");

        itemDepartureState.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {}));

        itemDepartureOwnerID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemDepartureOwnerID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemDepartureOwnerIDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemDepartureOwnerIDFocusLost(evt);
            }
        });

        itemDepartureIdentifiquer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        itemDepartureIdentifiquer.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                itemDepartureIdentifiquerFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemDepartureIdentifiquerFocusLost(evt);
            }
        });

        itemDepartureButton.setText("DAR SALIDA");
        itemDepartureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDepartureButtonActionPerformed(evt);
            }
        });

        goBackButton.setText("<-");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vehicleCheckInTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(developerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(itemDepartureState, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(itemDepartureButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(itemDepartureIdentifiquer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(itemDepartureOwnerID, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(vehicleCheckInTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(itemDepartureOwnerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemDepartureIdentifiquer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(itemDepartureState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(itemDepartureButton)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goBackButton)
                    .addComponent(developerLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setSelector(JComboBox<String> selector, ArrayList<Object> data, int index) {
        ArrayList<String> names = (ArrayList<String>) data.get(index);

        if (names != null && !names.isEmpty()) {
            names.forEach(name -> selector.addItem(name.toUpperCase()));
        } else {
            System.out.println("No se encontraron elementos para agregar al selector.");
        }
    }

    private void setStateSelector() {
        Checkout queryManagment = new Checkout();
        ArrayList<Object> states = BusinessItems.getStatesName();
        setSelector(itemDepartureState, states, 1);
    }


    private void itemDepartureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDepartureButtonActionPerformed
        // Definir los campos a verificar y los datos de la entrada
        String[] fields = {"estado", "cedula", "placa"};
        String[] itemInputData = new String[3];

        // Obtener y procesar los datos de entrada
        itemInputData[0] = IOOperations.parseVehicleStateToCode(itemDepartureState.getSelectedItem().toString().toLowerCase());
        itemInputData[1] = IOOperations.sanitizeInput(itemDepartureOwnerID.getText().toString());
        itemInputData[2] = IOOperations.sanitizeInput(itemDepartureIdentifiquer.getText().toString());

        // Validar si los campos están completos
        if (IOOperations.validateNonEmptyFields(this, itemInputData, fields)) {
            // Procesar el check-out del vehículo
            if (new BusinessModel().checkOut(this, itemInputData, fields)) {
                // Confirmar si se desea generar factura
                String[] options = {"Sí", "No"};
                int action = JOptionPane.showOptionDialog(
                        this,
                        "¿Desea generar factura?",
                        "Confirmar",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.QUESTION_MESSAGE,
                        null,
                        options,
                        options[0]
                );

                if (action == JOptionPane.YES_OPTION) {
                    try {
                        // Buscar los datos del vehículo en la base de datos
                        Item item = new Item();
                        String[] vehicleData = item.searchItem(itemInputData[2]);

                        // Verificar si se encontraron los datos del vehículo
                        if (vehicleData == null || vehicleData.length == 0) {
                            JOptionPane.showMessageDialog(this, "No se encontraron datos del vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
                            return;
                        }

                        // Obtener datos del negocio
                        Printing printingMethods = new Printing();
                        printingMethods.getBusinessData();

                        // Generar e imprimir la factura
                        printingMethods.print(vehicleData);
                    } catch (Exception e) {
                        // Manejo de excepciones para evitar caídas inesperadas
                        JOptionPane.showMessageDialog(this, "Ocurrió un error al generar la factura: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                        e.printStackTrace();
                    }
                }
            }
        }

    }//GEN-LAST:event_itemDepartureButtonActionPerformed

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        DashboardUI dashboard = new DashboardUI();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void itemDepartureOwnerIDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemDepartureOwnerIDFocusGained
        String placeholder = "Documento del cliente";

        // Eliminar el placeholder al ganar foco
        if (itemDepartureOwnerID.getText().equals(placeholder)) {
            itemDepartureOwnerID.setText("");
            itemDepartureOwnerID.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_itemDepartureOwnerIDFocusGained

    private void itemDepartureOwnerIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemDepartureOwnerIDFocusLost
        String placeholder = "Documento del cliente";

        // Restaurar el placeholder si el campo está vacío
        if (itemDepartureOwnerID.getText().isEmpty()) {
            itemDepartureOwnerID.setText(placeholder);
            itemDepartureOwnerID.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_itemDepartureOwnerIDFocusLost

    private void itemDepartureIdentifiquerFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemDepartureIdentifiquerFocusGained
        String placeholder = "Identificador del producto";

        // Eliminar el placeholder al ganar foco
        if (itemDepartureIdentifiquer.getText().equals(placeholder)) {
            itemDepartureIdentifiquer.setText("");
            itemDepartureIdentifiquer.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_itemDepartureIdentifiquerFocusGained

    private void itemDepartureIdentifiquerFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemDepartureIdentifiquerFocusLost
        String placeholder = "Identificador del producto";

        // Restaurar el placeholder si el campo está vacío
        if (itemDepartureIdentifiquer.getText().isEmpty()) {
            itemDepartureIdentifiquer.setText(placeholder);
            itemDepartureIdentifiquer.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_itemDepartureIdentifiquerFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemCheckOutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemCheckOutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemCheckOutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemCheckOutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemCheckOutUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel developerLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JButton itemDepartureButton;
    private javax.swing.JTextField itemDepartureIdentifiquer;
    private javax.swing.JTextField itemDepartureOwnerID;
    private javax.swing.JComboBox<String> itemDepartureState;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel vehicleCheckInTitleLabel;
    // End of variables declaration//GEN-END:variables
}
