/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import javax.swing.JOptionPane;
import network.Authentication;
import controller.User;
import network.Business;
import network.UserData;
import utilities.SystemAuth;

/**
 *
 * @author Felipe
 */
public class LoginUI extends javax.swing.JFrame {

    public LoginUI() {

        initComponents();
        SystemAuth systemAuth = new SystemAuth();

        if (systemAuth.validateSystemData()) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginLabel = new javax.swing.JLabel();
        loginEmailField = new javax.swing.JTextField();
        loginPasswordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        loginExitButtom = new javax.swing.JButton();
        branding = new javax.swing.JPanel();
        developerLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("login"); // NOI18N
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 24)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 255));
        loginLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginLabel.setText("INICIO DE SESION");
        getContentPane().add(loginLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 80));

        loginEmailField.setBackground(new java.awt.Color(255, 255, 255));
        loginEmailField.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        loginEmailField.setForeground(new java.awt.Color(0, 102, 153));
        loginEmailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginEmailField.setText("casanascastrofelipe@gmail.com");
        loginEmailField.setToolTipText("");
        loginEmailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginEmailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(loginEmailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 280, -1));

        loginPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        loginPasswordField.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        loginPasswordField.setForeground(new java.awt.Color(0, 102, 153));
        loginPasswordField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        loginPasswordField.setText("1234");
        getContentPane().add(loginPasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 280, -1));

        loginButton.setBackground(new java.awt.Color(0, 153, 51));
        loginButton.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("INICIAR SESION");
        loginButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, -1));

        loginExitButtom.setBackground(new java.awt.Color(204, 0, 0));
        loginExitButtom.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        loginExitButtom.setForeground(new java.awt.Color(255, 255, 255));
        loginExitButtom.setText("SALIR");
        loginExitButtom.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginExitButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginExitButtomActionPerformed(evt);
            }
        });
        getContentPane().add(loginExitButtom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 78, -1));

        branding.setBackground(new java.awt.Color(255, 255, 255));

        developerLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 2, 18)); // NOI18N
        developerLabel.setForeground(new java.awt.Color(0, 0, 0));
        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        javax.swing.GroupLayout brandingLayout = new javax.swing.GroupLayout(branding);
        branding.setLayout(brandingLayout);
        brandingLayout.setHorizontalGroup(
            brandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, brandingLayout.createSequentialGroup()
                .addComponent(developerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        brandingLayout.setVerticalGroup(
            brandingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(developerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        getContentPane().add(branding, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 360, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background.jpeg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 360, 250));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginEmailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginEmailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginEmailFieldActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // Obtiene los datos de la interfaz y los procesa
        String email = loginEmailField.getText().toLowerCase().trim();
        String password = loginPasswordField.getText().trim();

        // Instancia el objeto User y valida las credenciales
        if (new Authentication().auth(email, password)) {
            // Si el usuario es válido, obtiene y guarda la información del usuario
            new User().setData(new UserData().get(email, 1));

            // Obtiene la categoría de negocio
            new Business().getCategory();

            // Abre el Dashboard y cierra el Login
            openDashboard();
        } else {
            // Si las credenciales son incorrectas, muestra un mensaje
            showError("Correo y/o contraseña incorrectos");
        }
    }//GEN-LAST:event_loginButtonActionPerformed

    private void openDashboard() {
        DashboardUI dashboard = new DashboardUI();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.setVisible(false);
    }

    private void showError(String message) {
        JOptionPane.showMessageDialog(this, message);
    }

    private void loginExitButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginExitButtomActionPerformed
        System.exit(0);
    }//GEN-LAST:event_loginExitButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JPanel branding;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JButton loginButton;
    private javax.swing.JTextField loginEmailField;
    private javax.swing.JButton loginExitButtom;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField loginPasswordField;
    // End of variables declaration//GEN-END:variables
}
