/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterface;

import network.QueryManagment;
import corePackage.CheckoutDataProcessing;
import generalUtility.IOOperations;
import generalUtility.TimeMethods;

/**
 *
 * @author Felipe
 */
public class CashCheckoutUI extends javax.swing.JFrame {

    /**
     * Creates new form CashCheckout
     */
    public CashCheckoutUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratesTitleLabel = new javax.swing.JLabel();
        developerLabel = new javax.swing.JLabel();
        leftContainer = new javax.swing.JPanel();
        counterTitleLabel = new javax.swing.JLabel();
        carCounterLabel = new javax.swing.JLabel();
        motorcycleCounterLabel = new javax.swing.JLabel();
        bikeCounterLabel = new javax.swing.JLabel();
        carCounter = new javax.swing.JLabel();
        motorcycleCounter = new javax.swing.JLabel();
        bikeCounter = new javax.swing.JLabel();
        rightContainer = new javax.swing.JPanel();
        incomeTitleLabel = new javax.swing.JLabel();
        carIncomeLabel = new javax.swing.JLabel();
        motorcycleIncomeLabel = new javax.swing.JLabel();
        bikeIncomeLabel = new javax.swing.JLabel();
        carIncome = new javax.swing.JLabel();
        motorcycleIncome = new javax.swing.JLabel();
        bikeIncome = new javax.swing.JLabel();
        todayReport = new javax.swing.JButton();
        otherDayReport = new javax.swing.JButton();
        otherDayReportField = new javax.swing.JTextField();
        otherDaySearchReport = new javax.swing.JButton();
        goBackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        ratesTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        ratesTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratesTitleLabel.setText("CUADRE DE CAJA");

        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        counterTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        counterTitleLabel.setText("CONTEO VEHICULAR");

        carCounterLabel.setText("CARROS");

        motorcycleCounterLabel.setText("MOTOS");

        bikeCounterLabel.setText("BICICLETAS");

        carCounter.setText("----");

        motorcycleCounter.setText("----");

        bikeCounter.setText("----");

        javax.swing.GroupLayout leftContainerLayout = new javax.swing.GroupLayout(leftContainer);
        leftContainer.setLayout(leftContainerLayout);
        leftContainerLayout.setHorizontalGroup(
            leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftContainerLayout.createSequentialGroup()
                        .addComponent(counterTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftContainerLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(carCounter, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(motorcycleCounter, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftContainerLayout.createSequentialGroup()
                .addComponent(bikeCounterLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bikeCounter)
                .addContainerGap())
            .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftContainerLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(carCounterLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(motorcycleCounterLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(94, Short.MAX_VALUE)))
        );
        leftContainerLayout.setVerticalGroup(
            leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(counterTitleLabel)
                .addGap(18, 18, 18)
                .addComponent(carCounter)
                .addGap(18, 18, 18)
                .addComponent(motorcycleCounter)
                .addGap(18, 18, 18)
                .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bikeCounter)
                    .addComponent(bikeCounterLabel))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(leftContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(leftContainerLayout.createSequentialGroup()
                    .addGap(40, 40, 40)
                    .addComponent(carCounterLabel)
                    .addGap(18, 18, 18)
                    .addComponent(motorcycleCounterLabel)
                    .addContainerGap(43, Short.MAX_VALUE)))
        );

        incomeTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        incomeTitleLabel.setText("DINERO GENERADO");

        carIncomeLabel.setText("CARROS");

        motorcycleIncomeLabel.setText("MOTOS");

        bikeIncomeLabel.setText("BICICLETAS");

        carIncome.setText("----");

        motorcycleIncome.setText("----");

        bikeIncome.setText("----");

        javax.swing.GroupLayout rightContainerLayout = new javax.swing.GroupLayout(rightContainer);
        rightContainer.setLayout(rightContainerLayout);
        rightContainerLayout.setHorizontalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightContainerLayout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(carIncome)
                    .addComponent(motorcycleIncome)
                    .addComponent(bikeIncome))
                .addGap(12, 12, 12))
            .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightContainerLayout.createSequentialGroup()
                    .addGap(1, 1, 1)
                    .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(incomeTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                        .addGroup(rightContainerLayout.createSequentialGroup()
                            .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(bikeIncomeLabel)
                                .addComponent(carIncomeLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(motorcycleIncomeLabel, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        rightContainerLayout.setVerticalGroup(
            rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(carIncome)
                .addGap(18, 18, 18)
                .addComponent(motorcycleIncome)
                .addGap(18, 18, 18)
                .addComponent(bikeIncome)
                .addGap(10, 10, 10))
            .addGroup(rightContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(rightContainerLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(incomeTitleLabel)
                    .addGap(18, 18, 18)
                    .addComponent(carIncomeLabel)
                    .addGap(18, 18, 18)
                    .addComponent(motorcycleIncomeLabel)
                    .addGap(18, 18, 18)
                    .addComponent(bikeIncomeLabel)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        todayReport.setText("HOY");
        todayReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                todayReportActionPerformed(evt);
            }
        });

        otherDayReport.setText("OTRO");
        otherDayReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherDayReportActionPerformed(evt);
            }
        });

        otherDayReportField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        otherDayReportField.setEnabled(false);

        otherDaySearchReport.setText("BUSCAR");
        otherDaySearchReport.setEnabled(false);
        otherDaySearchReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherDaySearchReportActionPerformed(evt);
            }
        });

        goBackButton.setText("<-");
        goBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ratesTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(goBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(developerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(otherDayReportField)
                                    .addComponent(otherDaySearchReport, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(todayReport, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(otherDayReport, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(leftContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rightContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ratesTitleLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(rightContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(leftContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(todayReport)
                            .addComponent(otherDayReport))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherDayReportField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(otherDaySearchReport)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(developerLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(goBackButton, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void goBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackButtonActionPerformed
        //Regresa a la pagina principal
        DashboardUI dashboard = new DashboardUI();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_goBackButtonActionPerformed

    private void otherDayReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherDayReportActionPerformed
        //Activa el campo para ingresar la fecha
        if (!otherDayReportField.isEnabled()) {
            otherDayReportField.setEnabled(true);
            otherDaySearchReport.setEnabled(true);
        }
    }//GEN-LAST:event_otherDayReportActionPerformed

    private void todayReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_todayReportActionPerformed
        //Obtiene la fecha actual
        String actualDate = TimeMethods.formatDate();

        //Establece la fecha actual en el campo de texto
        otherDayReportField.setText(actualDate);

        //Desactiva el campo de texto y activa el boton de busqueda
        otherDayReportField.setEnabled(false);
        otherDaySearchReport.setEnabled(true);
    }//GEN-LAST:event_todayReportActionPerformed

    private void otherDaySearchReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherDaySearchReportActionPerformed
        // Obtiene la fecha ingresada y la formatea
        String dateToSearch = IOOperations.replaceSlash(otherDayReportField.getText());

        // Obtiene el conteo y los totales desde la base de datos
        QueryManagment queryCheckoutData = new QueryManagment();
        String[][] checkoutData = queryCheckoutData.getCheckoutData(dateToSearch);

        // Procesa los datos de checkout para obtener los conteos y totales por tipo de vehículo
        CheckoutDataProcessing checkoutDataProcessing = new CheckoutDataProcessing();
        double[] countedData = checkoutDataProcessing.getCountCheckoutLogs(checkoutData);

        // Actualiza los campos de la interfaz con los resultados
        carCounter.setText(String.valueOf(countedData[0]));
        motorcycleCounter.setText(String.valueOf(countedData[1]));
        bikeCounter.setText(String.valueOf(countedData[2]));
        carIncome.setText(String.valueOf(countedData[4]));
        motorcycleIncome.setText(String.valueOf(countedData[5]));
        bikeIncome.setText(String.valueOf(countedData[6]));
    }//GEN-LAST:event_otherDaySearchReportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashCheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashCheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashCheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashCheckoutUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashCheckoutUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bikeCounter;
    private javax.swing.JLabel bikeCounterLabel;
    private javax.swing.JLabel bikeIncome;
    private javax.swing.JLabel bikeIncomeLabel;
    private javax.swing.JLabel carCounter;
    private javax.swing.JLabel carCounterLabel;
    private javax.swing.JLabel carIncome;
    private javax.swing.JLabel carIncomeLabel;
    private javax.swing.JLabel counterTitleLabel;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JButton goBackButton;
    private javax.swing.JLabel incomeTitleLabel;
    private javax.swing.JPanel leftContainer;
    private javax.swing.JLabel motorcycleCounter;
    private javax.swing.JLabel motorcycleCounterLabel;
    private javax.swing.JLabel motorcycleIncome;
    private javax.swing.JLabel motorcycleIncomeLabel;
    private javax.swing.JButton otherDayReport;
    private javax.swing.JTextField otherDayReportField;
    private javax.swing.JButton otherDaySearchReport;
    private javax.swing.JLabel ratesTitleLabel;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JButton todayReport;
    // End of variables declaration//GEN-END:variables
}
