/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userInterface;

import corePackage.Parking;
import javax.swing.JOptionPane;
import corePackage.Rates;
import corePackage.User;

/**
 *
 * @author Felipe
 */
public class RatesUI extends javax.swing.JFrame {

    
    
    Parking parking = new Parking();

    public RatesUI() {
        initComponents();

        //Primero indica a ratesManagment para que obtenga las tarifas y luego indica a printRates para que las establezca
        Double[] rates = parking.getParkingRates();
        printRates(rates);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ratesTitleLabel = new javax.swing.JLabel();
        carRateLabel = new javax.swing.JLabel();
        motorcycleRateLabel = new javax.swing.JLabel();
        bikeRateLabel = new javax.swing.JLabel();
        carRate = new javax.swing.JLabel();
        motorcycleRate = new javax.swing.JLabel();
        bikeRate = new javax.swing.JLabel();
        ratesGoBackButton = new javax.swing.JButton();
        developerLabel = new javax.swing.JLabel();
        changeCarRates = new javax.swing.JButton();
        changeMotorcyclesRates = new javax.swing.JButton();
        changeBikeRates = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        ratesTitleLabel.setFont(new java.awt.Font("Gill Sans MT Condensed", 1, 20)); // NOI18N
        ratesTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ratesTitleLabel.setText("ADMINISTRADOR PRECIOS");

        carRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carRateLabel.setText("TARIFA CARRO: ");

        motorcycleRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        motorcycleRateLabel.setText("TARIFA MOTO: ");

        bikeRateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bikeRateLabel.setText("TARIFA BICICLETA: ");

        carRate.setText("-------");

        motorcycleRate.setText("-------");

        bikeRate.setText("-------");

        ratesGoBackButton.setText("VOLVER");
        ratesGoBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratesGoBackButtonActionPerformed(evt);
            }
        });

        developerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        developerLabel.setText("CASANAS SOFTWARE");

        changeCarRates.setText("CAMBIAR");
        changeCarRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeCarRatesActionPerformed(evt);
            }
        });

        changeMotorcyclesRates.setText("CAMBIAR");
        changeMotorcyclesRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeMotorcyclesRatesActionPerformed(evt);
            }
        });

        changeBikeRates.setText("CAMBIAR");
        changeBikeRates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeBikeRatesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carRateLabel)
                    .addComponent(motorcycleRateLabel)
                    .addComponent(bikeRateLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(carRate)
                        .addGap(18, 18, 18)
                        .addComponent(changeCarRates))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(motorcycleRate)
                            .addComponent(bikeRate))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(changeBikeRates)
                            .addComponent(changeMotorcyclesRates))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(ratesTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(developerLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(ratesGoBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ratesTitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carRateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(carRate)
                    .addComponent(changeCarRates))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motorcycleRateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(motorcycleRate)
                    .addComponent(changeMotorcyclesRates))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bikeRateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(bikeRate)
                    .addComponent(changeBikeRates))
                .addGap(18, 18, 18)
                .addComponent(ratesGoBackButton)
                .addGap(18, 18, 18)
                .addComponent(developerLabel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Trata cambiar la tarifa y vuelve a imprimir la nueva
    private void changeCarRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeCarRatesActionPerformed
        Rates rates = new Rates();
        double newRate = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva tarifa"));

        User user = new User();
        rates.updateRate(this, Integer.parseInt(user.getBusiness_id()), "carro", newRate);
        Double[] returnedRates = parking.getParkingRates();
        printRates(returnedRates);
    }//GEN-LAST:event_changeCarRatesActionPerformed

    //Trata cambiar la tarifa y vuelve a imprimir la nueva
    private void changeMotorcyclesRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeMotorcyclesRatesActionPerformed
        Rates rates = new Rates();
        double newRate = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva tarifa"));

        User user = new User();
        rates.updateRate(this, Integer.parseInt(user.getBusiness_id()), "moto", newRate);
        Double[] returnedRates = parking.getParkingRates();
        printRates(returnedRates);
    }//GEN-LAST:event_changeMotorcyclesRatesActionPerformed

    //Trata cambiar la tarifa y vuelve a imprimir la nueva
    private void changeBikeRatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeBikeRatesActionPerformed
        Rates rates = new Rates();
        
        double newRate = Double.parseDouble(JOptionPane.showInputDialog("Ingrese la nueva tarifa"));

        User user = new User();
        rates.updateRate(this, Integer.parseInt(user.getBusiness_id()), "bicicleta", newRate);
        Double[] returnedRates = parking.getParkingRates();
        printRates(returnedRates);
    }//GEN-LAST:event_changeBikeRatesActionPerformed

    private void ratesGoBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratesGoBackButtonActionPerformed
        DashboardUI dashboard = new DashboardUI();
        dashboard.setVisible(true);
        dashboard.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_ratesGoBackButtonActionPerformed

    //Obtiene las tarifas desde ratesManagment y asigna esos valores a los JLabel de tarifas
    public void printRates(Double[] rates) {
        carRate.setText(String.valueOf(rates[0]));
        motorcycleRate.setText(String.valueOf(rates[1]));
        bikeRate.setText(String.valueOf(rates[2]));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bikeRate;
    private javax.swing.JLabel bikeRateLabel;
    private javax.swing.JLabel carRate;
    private javax.swing.JLabel carRateLabel;
    private javax.swing.JButton changeBikeRates;
    private javax.swing.JButton changeCarRates;
    private javax.swing.JButton changeMotorcyclesRates;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JLabel motorcycleRate;
    private javax.swing.JLabel motorcycleRateLabel;
    private javax.swing.JButton ratesGoBackButton;
    private javax.swing.JLabel ratesTitleLabel;
    // End of variables declaration//GEN-END:variables
}
